import { FlowDiagram, type FlowStep, type FlowStepStatus } from "@/components/common/FlowDiagram";
import {
  AI_PROVIDER_LABELS,
  VOICE_PROVIDER_LABELS,
  type AIProviderName,
  type JobApproval,
  type JobStatus,
  type QualityReport,
  type VoiceProviderName,
  type YouTubePublication,
} from "@/types";

const LATE_PIPELINE_STATUSES: JobStatus[] = [
  "generating_thumbnail",
  "quality_check",
  "ready",
  "awaiting_approval",
  "approved",
  "uploading",
  "processing",
  "published",
];

const SCRIPT_DONE_STATUSES: JobStatus[] = [
  "script_ready",
  "script_review",
  "generating_voice",
  "voice_ready",
  "generating_visuals",
  "generating_subtitles",
  "rendering",
  "video_validation",
  "video_ready",
  ...LATE_PIPELINE_STATUSES,
];

const VOICE_DONE_STATUSES: JobStatus[] = [
  "voice_ready",
  "generating_visuals",
  "generating_subtitles",
  "rendering",
  "video_validation",
  "video_ready",
  ...LATE_PIPELINE_STATUSES,
];

const VISUALS_DONE_STATUSES: JobStatus[] = [
  "generating_subtitles",
  "rendering",
  "video_validation",
  "video_ready",
  ...LATE_PIPELINE_STATUSES,
];

const SUBTITLES_DONE_STATUSES: JobStatus[] = ["rendering", "video_validation", "video_ready", ...LATE_PIPELINE_STATUSES];

const RENDER_DONE_STATUSES: JobStatus[] = ["video_validation", "video_ready", ...LATE_PIPELINE_STATUSES];

const VALIDATION_DONE_STATUSES: JobStatus[] = ["video_ready", ...LATE_PIPELINE_STATUSES];

function getScriptStageStatus(status: JobStatus): FlowStepStatus {
  if (status === "generating_script" || status === "regenerating") return "active";
  if (SCRIPT_DONE_STATUSES.includes(status)) return "done";
  return "waiting";
}

function getVoiceStageStatus(status: JobStatus): FlowStepStatus {
  if (status === "generating_voice") return "active";
  if (VOICE_DONE_STATUSES.includes(status)) return "done";
  return "waiting";
}

function getVisualsStageStatus(status: JobStatus): FlowStepStatus {
  if (status === "generating_visuals") return "active";
  if (VISUALS_DONE_STATUSES.includes(status)) return "done";
  return "waiting";
}

function getSubtitlesStageStatus(status: JobStatus): FlowStepStatus {
  if (status === "generating_subtitles") return "active";
  if (SUBTITLES_DONE_STATUSES.includes(status)) return "done";
  return "waiting";
}

function getRenderStageStatus(status: JobStatus): FlowStepStatus {
  if (status === "rendering") return "active";
  if (RENDER_DONE_STATUSES.includes(status)) return "done";
  return "waiting";
}

function getValidationStageStatus(status: JobStatus): FlowStepStatus {
  if (status === "video_validation") return "active";
  if (VALIDATION_DONE_STATUSES.includes(status)) return "done";
  return "waiting";
}

export interface PipelinePreviewProps {
  status: JobStatus;
  scriptProvider?: AIProviderName | null;
  voiceProvider?: VoiceProviderName | null;
  renderTemplate?: string | null;
  qualityReport?: QualityReport | null;
  approval?: JobApproval | null;
  youtube?: YouTubePublication | null;
}

function capitalize(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

/**
 * Workflow visualization for the Job Details page. Script, Voice, Visuals,
 * Subtitles, Rendering, and Validation all reflect real progress as of
 * Phase 5. Quality Check and Telegram Approval reflect real progress as of
 * Phases 9/10 — Thumbnail and YouTube/Analytics remain "Waiting" since no
 * later engine consumes the job yet.
 */
export function PipelinePreview({
  status,
  scriptProvider,
  voiceProvider,
  renderTemplate,
  qualityReport,
  approval,
  youtube,
}: PipelinePreviewProps) {
  const scriptStatus = getScriptStageStatus(status);
  const scriptHint =
    scriptStatus === "done" && scriptProvider
      ? `Generated by ${AI_PROVIDER_LABELS[scriptProvider]}`
      : scriptStatus === "active"
        ? "Generating your script…"
        : undefined;

  const voiceStatus = getVoiceStageStatus(status);
  const voiceHint =
    voiceStatus === "done" && voiceProvider
      ? `Generated by ${VOICE_PROVIDER_LABELS[voiceProvider]}`
      : voiceStatus === "active"
        ? "Generating narration audio…"
        : voiceStatus === "waiting" && scriptStatus === "done"
          ? "Waiting for Voice Engine"
          : undefined;

  const visualsStatus = getVisualsStageStatus(status);
  const visualsHint =
    visualsStatus === "done" && renderTemplate
      ? `${capitalize(renderTemplate)} template`
      : visualsStatus === "active"
        ? "Choosing backgrounds and templates…"
        : undefined;

  const subtitlesStatus = getSubtitlesStageStatus(status);
  const subtitlesHint = subtitlesStatus === "active" ? "Timing captions to narration audio…" : undefined;

  const renderStatus = getRenderStageStatus(status);
  const renderHint = renderStatus === "active" ? "Rendering scenes with Remotion…" : undefined;

  const validationStatus = getValidationStageStatus(status);
  const validationHint = validationStatus === "active" ? "Checking the output file…" : undefined;

  // A quality report or approval record, once real, stays "done" regardless
  // of what job.status has since moved on to (e.g. a job that's since been
  // approved/rejected still genuinely passed/warned its quality check).
  const qualityStatus: FlowStepStatus = qualityReport ? "done" : status === "quality_check" ? "active" : "waiting";
  const qualityHint = qualityReport
    ? `${qualityReport.status} · ${qualityReport.score}/100`
    : qualityStatus === "active"
      ? "Analyzing the rendered video…"
      : undefined;

  const approvalStatus: FlowStepStatus =
    approval?.status === "approved" || approval?.status === "rejected"
      ? "done"
      : status === "awaiting_approval"
        ? "active"
        : "waiting";
  const approvalHint =
    approval?.status === "approved"
      ? "Approved on Telegram"
      : approval?.status === "rejected"
        ? `Rejected — ${approval.reason ?? "no reason recorded"}`
        : approvalStatus === "active"
          ? "Sent to Telegram — waiting on your decision"
          : "You watch the video and approve or reject it.";

  const youtubeStatus: FlowStepStatus = youtube?.status === "uploaded" ? "done" : status === "uploading" ? "active" : "waiting";
  const youtubeHint =
    youtube?.status === "uploaded"
      ? `Published (${youtube.privacyStatus})`
      : youtube?.status === "failed"
        ? `Upload failed — ${youtube.lastError ?? "see the Publish card"}`
        : youtubeStatus === "active"
          ? "Uploading to YouTube…"
          : undefined;

  const steps: FlowStep[] = [
    { label: "Script", tone: "automatic", status: scriptStatus, hint: scriptHint },
    { label: "Voice", tone: "automatic", status: voiceStatus, hint: voiceHint },
    { label: "Visuals", tone: "automatic", status: visualsStatus, hint: visualsHint },
    { label: "Subtitles", tone: "automatic", status: subtitlesStatus, hint: subtitlesHint },
    { label: "Rendering", tone: "automatic", status: renderStatus, hint: renderHint },
    { label: "Video Validation", tone: "automatic", status: validationStatus, hint: validationHint },
    { label: "Thumbnail", tone: "automatic", status: "waiting" },
    { label: "Quality Check", tone: "automatic", status: qualityStatus, hint: qualityHint },
    { label: "Telegram Approval", tone: "manual", status: approvalStatus, hint: approvalHint },
    { label: "YouTube", tone: "automatic", status: youtubeStatus, hint: youtubeHint },
    { label: "Analytics", tone: "automatic", status: "waiting" },
  ];

  return <FlowDiagram steps={steps} />;
}
